version: "3.4"
services:

  web:
    image: scv-web
    environment:
      - API_URL=${API_URL}
      - USE_SELF_SIGNED_SSL=${USE_SELF_SIGNED_SSL}
      - IpFilterRules=${IpFilterRules}
      - RealIpFrom=${RealIpFrom}
      - WEB_BASE_HREF=${WEB_BASE_HREF}
      - IncludeSiteminderHeaders=${IncludeSiteminderHeaders}
    ports:
      - 8080:8080
    depends_on:
      - api

  api:
    image: scv-api
    environment: 
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - FileServicesClient__Username=${FileServicesClientUsername}
      - FileServicesClient__Password=${FileServicesClientPassword}
      - FileServicesClient__Url=${FileServicesClientUrl}
      - LookupServicesClient__Username=${LookupServicesClientUsername}
      - LookupServicesClient__Password=${LookupServicesClientPassword}
      - LookupServicesClient__Url=${LookupServicesClientUrl}
      - LocationServicesClient__Username=${LocationServicesClientUsername}
      - LocationServicesClient__Password=${LocationServicesClientPassword}
      - LocationServicesClient__Url=${LocationServicesClientUrl}
      - Request__ApplicationCd=${RequestApplicationCd}
      - Request__AgencyIdentifierId=${RequestAgencyIdentifierId}
      - Request__PartId=${RequestPartId}
      - Request__GetUserLoginDefaultAgencyId=${RequestGetUserLoginDefaultAgencyId}
      - Auth__UserId=${USER_ID}
      - Auth__UserPassword=${USER_PASSWORD}
      - Auth__AllowSiteMinderUserType=${ALLOW_SITE_MINDER_USER_TYPE}
      - DatabaseConnectionString=${DatabaseConnectionString}
      - DataProtectionKeyEncryptionKey=${DataProtectionKeyEncryptionKey}
      - Keycloak__Client=${KeycloakClient}
      - Keycloak__Authority=${KeycloakAuthority}
      - Keycloak__Secret=${KeycloakSecret}
      - Keycloak__Audience=${KeycloakAudience}
      - SiteMinderLogoutUrl=${SiteMinderLogoutUrl}
      - UserServicesClient__Username=${UserServicesClientUsername}
      - UserServicesClient__Password=${UserServicesClientPassword}
      - UserServicesClient__Url=${UserServicesClientUrl}
      - Keycloak__PresReqConfId=${KeycloakPresReqConfId}
      - Keycloak__VcIdpHint=${KeycloakVcIdpHint}
    ports:
      - 5000:5000
    volumes:
      - ./seed:/opt/app-root/data
    depends_on:
      - db
    command: >
      /bin/bash -c "
        echo Waiting for the database service to start up ...;
        sleep 10;
        /usr/libexec/s2i/run;"

  db:
    image: centos/postgresql-12-centos8
    environment:
      - POSTGRESQL_USER=${POSTGRESQL_USER}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_ADMIN_PASSWORD=${POSTGRESQL_ADMIN_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./tmp:/tmp2